baseURL: "https://devopera.ai/"
theme: "up-business-theme"
languageCode: "en-us"

title: "DevOpera"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "DevOpera"
  description: "AI-powered DevOps magic! Effortlessly generate config files & optimize workflows. Unleash productivity!"
  images: 
    - "images/hero-image.png"

  logo: "https://cdn.thekrishna.in/img/logo/devopera/DevOpera_transparent.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "Purdue University, 610 Purdue Mall, West Lafayette, IN, 47907"

  contact:
    - "reach@devopera.ai"

  copyright: "© 2022 DevOpera, All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
