baseURL: https://temp.devopera.ai/
languageCode: en-us
title: DevOpera

module:
  # uncomment line below for local development of module
  # workspace: hugo.work
  imports:
    path: github.com/StefMa/hugo-fresh


googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: DevOpera - AI for DevOps.
    # Hero subtitle (optional)
    subtitle: Turbocharge your DevOps Instrastructure! Harness LLMs to auto-generate Ansible playbooks, CI/CD pipelines, and more. 
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/devops-2.svg
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    # clientlogos:
    # - logo: systek
    #   url: https://google.com
    # - logo: tribe
    #   url: https://stefma.github.io/hugo-fresh/
    # - logo: kromo
    #   url: https://github.com/StefMa/hugo-fresh
    # - logo: infinite
    #   url: https://hugo-fresh.vercel.app/
    # - logo: gutwork
    #   url: https://bulma.io/
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /
  - title: Pricing
    url: /
  - title: Contact Us
    url: /
    button: true
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section1:
    title: Revolutionize DevOps
    subtitle: with AI-powered automation
    tiles:
    - title: Config File Generation
      icon: mouse-globe
      text: LLMs auto-generate Docker-compose, Ansible playbooks & more
      url: /
      buttonText: Learn More
    - title: Cloud Optimization
      icon: laptop-cloud
      text: Streamline workflows, boost efficiency across cloud platforms
      url: /
      buttonText: Get started
    # - title: AI-Driven Insights
    #   icon: plug-cloud
    #   text: Leverage AI for anomaly detection & resource optimization
    #   url: /
    #   buttonText: Get started
    - title: Privacy and Security
      icon: plug-cloud
      text: With locally deployed LLaMA models, we ensure absolute confidentiality.
      url: /
      buttonText: Get started
  # section2:
  #   title: Empower DevOps Engineers
  #   subtitle: with cutting-edge technology
  #   features:
  #   - title: AI-Enhanced Interface
  #     text: Unify and simplify DevOps tasks with AI and LLM-driven solutions
  #     icon: laptop-globe
  #   - title: Seamless Integrations
  #     text: Effortlessly integrate with existing DevOps tools, minimizing disruption
  #     icon: doc-sync
  #   - title: Future-Proof Solution
  #     text: Stay ahead of the curve with continuous updates and improvements
  #     icon: mobile-feed
  section3:
    title: One DevOpera Platform
    subtitle: Transforming DevOps Experience
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  section5:
    title: Connect with us
    subtitle:  Join Our Waitlist, Request a Demo, and More.
    buttonText: Send Message
    action: https://formspree.io/f/mrgvrypl
    method: POST
  footer:
    # Logo (from /images/logos/___)
    logo: logo_white.png # fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/devopera-ai
      # Icons are from Font Awesome
      icon: github
    - link: https://twitter.com/devopera_ai
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
      column2:
        title: "Contact Us"
        links:
        - text: Email us
          link: mailto://reach@devopera.ai
        - text: Join our beta waitlist
          link: mailto://beta@devopera.ai
      #   - text: Admin guide
      #     link: /
      #   - text: Developers
      #     link: /
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
